name: Bug Report
description: You're experiencing an issue with Wesql-server that is different than the documented behavior.
title: "[Bug Report] "
labels: ["Type: Bug", "Needs Triage"]
body:
  - type: textarea
    id: overview-of-the-issue
    attributes:
      label: Overview of the Issue
      description: A paragraph or two about the issue you're experiencing.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: |
        A paragraph or two about the issue you're experiencing.
    validations:
      required: true

  - type: textarea
    id: binary-version
    attributes:
      label: Binary Version
      description: |
        Tell us which version of wesql-server you're using.
      render: sh
    validations:
      required: true

  - type: textarea
    id: os-and-env
    attributes:
      label: Operating System and Environment details
      description: |
        OS, Architecture, and any other information you can provide about the environment.
        Example:
        - Operating system (output of `cat /etc/os-release`)
        - Kernel version (output of `uname -sr`)
        - Architecture (output of `uname -m`)
      render: sh
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Fragments
      description: Include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the gist (https://gist.github.com/) of the log instead of posting it in the issue. This will be automatically formatted into code, so no need for backticks.
      render: sh
